baseURL = "http://digiplasty.com"
languageCode = "en-us"
title = 'digiplasty'
theme = "PaperMod"

[params]
  env = "production"
  disableGoogleAnalytics = true
  CSS = ["css/custom/custom.css"]

publishDir = "public"
